# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/54bd30c6-6a50-4912-8c53-f750eb6087ea";
      fsType = "btrfs";
      options = [
        "noatime"
        "compress=zstd:1"
        # "space_cache=v2"
        # "autodefrag"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1117-E839";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/51f88f3b-e18a-4692-9d68-09c278807307";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/08f67253-c744-477b-a3ce-c9ba18f5f6b8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
